# Generated by Django 3.2 on 2021-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_auto_20210428_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question1',
            field=models.IntegerField(choices=[('Poor', 1), ('Average', 2), ('Good', 3), ('Very Good', 4), ('Excellent', 5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question2',
            field=models.IntegerField(choices=[('Poor', 1), ('Average', 2), ('Good', 3), ('Very Good', 4), ('Excellent', 5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question3',
            field=models.IntegerField(choices=[('Poor', 1), ('Average', 2), ('Good', 3), ('Very Good', 4), ('Excellent', 5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question4',
            field=models.IntegerField(choices=[('Poor', 1), ('Average', 2), ('Good', 3), ('Very Good', 4), ('Excellent', 5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question5',
            field=models.IntegerField(choices=[('Poor', 1), ('Average', 2), ('Good', 3), ('Very Good', 4), ('Excellent', 5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question6',
            field=models.IntegerField(choices=[('Poor', 1), ('Average', 2), ('Good', 3), ('Very Good', 4), ('Excellent', 5)]),
        ),
    ]
