# Generated by Django 3.2 on 2021-04-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_auto_20210429_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question1',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question2',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question3',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question4',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question5',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question6',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')]),
        ),
    ]
