# Generated by Django 3.2 on 2021-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_auto_20210429_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question1',
            field=models.IntegerField(choices=[(1, '🤬'), (2, '🙁'), (3, '😶'), (4, '😁'), (5, '😍')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question2',
            field=models.IntegerField(choices=[(1, '🤬'), (2, '🙁'), (3, '😶'), (4, '😁'), (5, '😍')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question3',
            field=models.IntegerField(choices=[(1, '🤬'), (2, '🙁'), (3, '😶'), (4, '😁'), (5, '😍')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question4',
            field=models.IntegerField(choices=[(1, '🤬'), (2, '🙁'), (3, '😶'), (4, '😁'), (5, '😍')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question5',
            field=models.IntegerField(choices=[(1, '🤬'), (2, '🙁'), (3, '😶'), (4, '😁'), (5, '😍')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question6',
            field=models.IntegerField(choices=[(1, '🤬'), (2, '🙁'), (3, '😶'), (4, '😁'), (5, '😍')]),
        ),
    ]
