# Generated by Django 3.2 on 2021-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_auto_20210429_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question1',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
    ]
