# Generated by Django 3.2 on 2021-04-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_alter_feedback_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question2',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, "I don't know"), (0, 'No')]),
        ),
    ]
