# Generated by Django 3.2 on 2021-04-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0008_alter_feedback_question2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question4',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Agree'), (3, 'Neutral'), (4, 'Disagree'), (5, 'Strongly Disagree')]),
        ),
    ]
