# Generated by Django 3.2 on 2021-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0010_alter_feedback_question5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question1',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
    ]
