# Generated by Django 3.2 on 2021-05-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0011_alter_feedback_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question4',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')]),
        ),
    ]
