# Generated by Django 3.2 on 2021-05-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0015_auto_20210527_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
    ]
